name: Cypress Tests

on:
  push:
    branches:
      - main
      - solution
  pull_request:
    branches:
      - main
      - solution

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Start server (background process)
        run: npm start &

      - name: Wait for server (optional)
        run: while ! nc -z localhost 3002; do sleep 2; done

      - name: Clean and Generate Reports Folders
        run: npm run clean:reports

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate test reports
        run: npm run posttest

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports/mochareports/
